=== tanyakurdelchuk/DistributedComputing/DistributedComputing/secondpart/lab_1/src/main/java/second/module/first/shop.dtd
<!ELEMENT Shop (Genre*)>
        <!ELEMENT Genre (Movie*)>
        <!ELEMENT Movie (#PCDATA)>
        <!ATTLIST Genre
                id ID #REQUIRED
                name CDATA #REQUIRED
                >
        <!ATTLIST Movie
                id ID #REQUIRED
                genreId IDREF #REQUIRED
                name CDATA #REQUIRED
                releaseYear CDATA #REQUIRED
                >

=== tanyakurdelchuk/DistributedComputing/DistributedComputing/secondpart/lab_1/src/main/java/second/module/first/shop.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?><!DOCTYPE Shop SYSTEM "shop.dtd">
<Shop><Genre id="genre3" name="Detective"><Movie genreId="genre3" id="id3" name="Sherlock" releaseYear="2008"/><Movie genreId="genre3" id="id3" name="Sherlock" releaseYear="2008"/><Movie genreId="genre3" id="id4" name="" releaseYear="2008"/><Movie genreId="genre3" id="id4" name="" releaseYear="2008"/></Genre><Genre id="genre1" name="Comedy"><Movie genreId="genre1" id="id1" name="Baron" releaseYear="2000"/></Genre><Genre id="genre2" name="Action"><Movie genreId="genre2" id="id2" name="Bachelor" releaseYear="2018"/></Genre><Genre id="genre0" name="Horror"><Movie genreId="genre0" id="id0" name="Scream" releaseYear="1987"/></Genre></Shop>
